### ISSUE TITLE
Unexpected unknown function "px-to-rem"  scss/function-no-unknown

### ISSUE THREAD

**Issue by lijianru** [stylelint-scss/stylelint-config-recommended-scss#206]
I defined a px-to-rem function, but an error will be reported when it is referenced in another style file.

```scss
// lib/css/px-to-rem.scss
@use 'sass:list';

$base-font-size: 16px;

@function px-to-rem($values...) {
  $rem-values: ();
  @each $value in $values {
    @if type-of($value) == number and unit($value) == 'px' {
      $rem-value: calc($value / $base-font-size) + rem;
      $rem-values: list.append($rem-values, $rem-value);
    } @else {
      $rem-values: list.append($rem-values, $value);
    }
  }
  @return $rem-values;
}

// other.scss
@import 'lib/css/px-to-rem';

.container {
  margin-bottom: px-to-rem(24px);
}

// Unexpected unknown function "px-to-rem"  scss/function-no-unknown
```
