### ISSUE TITLE
stylelint-config-recommended-scss "doesn't provide postcss, requested by postcss-scss"

### ISSUE THREAD

**Issue by pgnd** [stylelint-scss/stylelint-config-recommended-scss#89]
with

```
yarn --version
	3.2.0-rc.8

yarn info --name-only| egrep "postcss@|postcss-scss|stylelint-config"
	├─ postcss@npm:8.4.5
	├─ postcss-scss@npm:4.0.2
	├─ stylelint-config-standard-scss@npm:3.0.0
```

and yarn exec reports,
```
yarn
	➤ YN0000: ┌ Resolution step
???	➤ YN0002: │ stylelint-config-recommended-scss@npm:5.0.2 [577f4] doesn't provide postcss (p9d028), requested by postcss-scss
	➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
	➤ YN0000: └ Completed
	➤ YN0000: ┌ Fetch step
	➤ YN0000: └ Completed in 0s 210ms
	➤ YN0000: ┌ Link step
	➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
	➤ YN0000: └ Completed
	➤ YN0000: Done with warnings in 0s 498ms
```

where
```
yarn explain peer-requirements p9d028
	➤ YN0000: stylelint-config-recommended-scss@npm:5.0.2 [577f4] doesn't provide postcss, breaking the following requirements:

	➤ YN0000: postcss-scss@npm:4.0.2 [54149] → ^8.3.3 ✘
```

is this a fix needed in s-c-r-s? postcss*? or local config?

**Comment by kherock** [comment]
I'm seeing this as well, the peer is missing in both places. I need this in my `packageExtensions` for the preset to work

```yaml
packageExtensions:
  stylelint-config-recommended-scss@*:
    peerDependencies:
      postcss: '8'
  stylelint-config-standard-scss@*:
    peerDependencies:
      postcss: '8'
```
